credentials:
  usernames:
    jsmith:
      email: test@gmail.com
      name: Test
      password: abc # To be replaced with hashed password
    rbriggs:
      email: test@gmail.com
      name: Test
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - test@gmail.com
